# Generated by Django 2.2 on 2021-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(default='', max_length=100)),
                ('dept', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
